### ISSUE TITLE
Support for including in app and linked library

### ISSUE THREAD

**Issue by fumoboy007** [nicklockwood/MustOverride#1]
If this is used in an app _and_ a library the app links to, then there will be a name collision. I don’t know if it is possible to get around this. Maybe you know. :smiley:

**Comment by nicklockwood** [comment]
Unfortunately this is a general problem with with way static libraries work in C.

If your app includes a library that you know includes MustOverride, you don't need to include MustOverride in your app as well, so you can just remove it. If the library doesn't expose the header, you can include MustOverride.h but not MustOverride.m in your app, so you can still use the macro in your code without the collision.

Unfortunately, that won't help if your app imports two libraries, _both_ of which include MustOverride.

Another option is to use a dependency manager like Cocoapods. It will automatically ensure you only get one copy of each library included in your app.

**Comment by fumoboy007** [comment]
Oh yeah forgot about CocoaPods.
